name: 'Docker Compose Cache'
description: 'Caches Docker images from Docker Compose files to speed up builds. Supports digest checks and image exclusion.'
author: 'Seiji Kohara (https://github.com/seijikohara)'
branding:
  icon: 'zap'
  color: 'blue'
inputs:
  compose-files:
    description: >
      Path(s) to the Docker Compose file(s).
      Specify multiple files using multiline string with pipe (|):
        compose-files: |
          docker-compose.yml
          docker-compose.prod.yml
      If omitted, defaults to searching for default compose files.
    required: false
  exclude-images:
    description: >
      Images to exclude from caching. Supports glob patterns with '*' (any chars) and '?' (single char).
      Specify multiple patterns using multiline string with pipe (|):
        exclude-images: |
          nginx:*
          *:latest
          ghcr.io/myorg/*
    required: false
  cache-key-prefix:
    description: 'Prefix for the generated cache key.'
    required: false
    default: 'docker-compose-image'
  skip-digest-verification:
    description: 'Skip verifying image digests against the remote registry. When enabled, cached images will be used without checking if newer versions are available. This speeds up execution but may result in using outdated images.'
    required: false
    default: 'false'
  force-refresh:
    description: 'Ignore existing cache and pull all images fresh from the registry. Pulled images will still be saved to cache for future runs. Useful for security updates or debugging cache issues.'
    required: false
    default: 'false'
  skip-latest-check:
    description: '[DEPRECATED] Use skip-digest-verification instead. This option will be removed in a future major version.'
    required: false
    default: 'false'
    deprecationMessage: 'skip-latest-check is deprecated. Use skip-digest-verification instead.'
  additional-images:
    description: >
      Additional images to include in caching that are not defined in the compose files. One image per line.
    required: false
  container-runtime:
    description: 'Container runtime to use for caching operations. Supported values: "docker" (default), "podman".'
    required: false
    default: 'docker'
outputs:
  cache-hit:
    description: "Boolean value ('true' or 'false') indicating if *all* required images were restored from cache (and digests matched). Example: 'true'"
  image-list:
    description: 'JSON array of image details with information about each image. Example: ''[{"name":"mysql:8.0","platform":"linux/amd64","status":"Cached","size":524288000,"digest":"sha256:abc123...","processingTimeMs":1200.5,"cacheKey":"docker-compose-image-mysql-8.0-linux-amd64-none-abc123def456"},{"name":"redis:alpine","platform":"linux/amd64","status":"Pulled","size":32768000,"digest":"sha256:def456...","processingTimeMs":3500.2,"cacheKey":"docker-compose-image-redis-alpine-linux-amd64-none-def456789abc"}]'''
runs:
  using: 'node20'
  main: 'dist/index.js'
